# Generated by Django 4.2.17 on 2024-12-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'MOCK_DATA',
            },
        ),
        migrations.CreateModel(
            name='PropertySummary',
            fields=[
                ('property_id', models.UUIDField(primary_key=True, serialize=False)),
                ('summary', models.TextField()),
            ],
            options={
                'db_table': 'LLM_app_propertysummary',
            },
        ),
    ]
