# Generated by Django 4.2.17 on 2025-01-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLM_app_propertyreview',
            fields=[
                ('property_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating', models.FloatField(null=True)),
                ('review', models.TextField()),
            ],
            options={
                'db_table': 'LLM_app_propertyreview',
            },
        ),
        migrations.CreateModel(
            name='LLM_app_propertysummary',
            fields=[
                ('property_id', models.UUIDField(primary_key=True, serialize=False)),
                ('summary', models.TextField()),
            ],
            options={
                'db_table': 'LLM_app_propertysummary',
            },
        ),
    ]
